services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_app
    volumes:
      - .:/var/www
    expose:
      - "9000"
    networks:
      - lumen_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: lumen_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf.d:/etc/nginx/conf.d
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - lumen_network

  db:
    image: mysql:8.0
    container_name: lumen_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lumen
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - lumen_network

networks:
  lumen_network:
    driver: bridge
